// Generated by CoffeeScript 1.3.1
(function() {
  var Dialog,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Dialog = (function() {

    Dialog.name = 'Dialog';

    function Dialog(dialog) {
      var _this = this;
      this.dialog = dialog;
      this.close = __bind(this.close, this);

      this.open = __bind(this.open, this);

      this.name = $('#star-name', this.dialog);
      this.vmag = $('#star-vmag', this.dialog);
      this.cicnt = $('#user-count', this.dialog);
      this.vmag_suffix = '等星';
      this.cicnt_suffix = '人がチェックインしてます';
      this.close_btn = $('#close-btn', this.dialog);
      this.close_btn.on('click', function() {
        _this.close();
        return false;
      });
    }

    Dialog.prototype.open = function(name, vmag, checkin_count) {
      this.name.text(name);
      this.vmag.text(vmag + this.vmag_suffix);
      this.cicnt.text(checkin_count + this.cicnt_suffix);
      return this.dialog.slideDown();
    };

    Dialog.prototype.close = function() {
      return this.dialog.slideUp();
    };

    return Dialog;

  })();

}).call(this);
